import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, join, relative, resolve } from "node:path";

import type {
  AgentDescriptor,
  ExecutionManifest,
  ForgeRepo,
  ManifestTask,
  WorkforceCompileOptions,
  WorkforceCompileResult,
} from "./types.ts";

function slug(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9-]+/g, "-").replace(/^-+|-+$/g, "");
}

function safeTaskNodeId(taskId: string): string {
  return `task-${taskId.toLowerCase().replace(/[^a-z0-9-]+/g, "-")}`;
}

function tierForModel(model: string | undefined): "small" | "medium" | "large" {
  const value = (model ?? "").toLowerCase();
  if (!value) return "medium";
  if (value.includes("mini") || value.includes("haiku") || value.includes("flash") || value.includes("small")) return "small";
  if (value.includes("opus") || /\bgpt-5(?!-mini)\b/.test(value) || value.includes("large") || value.includes("max")) return "large";
  return "medium";
}

function parseManifest(path: string): ExecutionManifest {
  return JSON.parse(readFileSync(path, "utf8")) as ExecutionManifest;
}

function flattenTasks(manifest: ExecutionManifest): ManifestTask[] {
  return manifest.phases.flatMap((phase) => phase.tasks);
}

function pickFallbackAgent(agents: AgentDescriptor[]): string | undefined {
  return agents[0]?.name;
}

function ensureDir(path: string): void {
  mkdirSync(path, { recursive: true });
}

function buildWorkflow(
  manifest: ExecutionManifest,
  manifestPath: string,
  fallbackAgent: string | undefined,
  warnings: string[],
  workflowId: string,
  retryMaxAttempts: number,
) {
  const tasks = flattenTasks(manifest);
  const nodeIds = tasks.map((task) => safeTaskNodeId(task.id));

  type WorkflowNode =
    | {
      id: string;
      type: "agent";
      agent: string;
      action: string;
      output: string;
      retry: { maxAttempts: number };
      next: string;
    }
    | {
      id: "end";
      type: "end";
    };

  const nodes: WorkflowNode[] = tasks.map((task, index) => {
    const owner = task.ownerAgent ?? fallbackAgent;
    if (!task.ownerAgent) {
      warnings.push(`Task ${task.id} has no ownerAgent; using '${owner ?? "unknown"}'.`);
    }
    if (!owner) {
      throw new Error(`Cannot build workflow: no agents are available for task ${task.id}.`);
    }

    const next = nodeIds[index + 1] ?? "end";
    return {
      id: nodeIds[index]!,
      type: "agent" as const,
      agent: owner,
      action: task.description || task.title,
      output: `task.${task.id}.output`,
      retry: { maxAttempts: retryMaxAttempts },
      next,
    };
  });

  nodes.push({ id: "end", type: "end" });

  return {
    id: workflowId,
    name: "Agent Forge Build Workflow",
    description: "Generated from docs/EXECUTION-MANIFEST.json by forge-workforce-compiler.",
    start: nodeIds[0] ?? "end",
    state: {
      sourceManifest: manifestPath,
      generatedAt: new Date().toISOString(),
    },
    nodes,
  };
}

export function compileWorkforcePackage(repo: ForgeRepo, options: WorkforceCompileOptions = {}): WorkforceCompileResult {
  const manifest = parseManifest(repo.manifestPath);
  const warnings = [...repo.warnings, ...(manifest.warnings ?? [])];

  const repoName = slug(basename(repo.repoRoot));
  const packageId = options.packageId ?? `dev.agent-forge.${repoName || "project"}`;
  const packageName = options.packageName ?? `Agent Forge Workforce (${basename(repo.repoRoot)})`;
  const packageVersion = options.packageVersion ?? "0.1.0";
  const workflowId = options.workflowId ?? "forge-build";
  const workflowRetryMaxAttempts = options.workflowRetryMaxAttempts ?? 1;

  const outputDir = resolve(options.outputDir ?? join(repo.repoRoot, "dist"));
  const workforceDir = join(outputDir, `${slug(packageId)}.workforce`);
  const agentsDir = join(workforceDir, "agents");
  const skillsDir = join(workforceDir, "skills");
  const workflowsDir = join(workforceDir, "workflows");

  ensureDir(agentsDir);
  ensureDir(skillsDir);
  ensureDir(workflowsDir);

  const fallbackAgent = pickFallbackAgent(repo.agents);
  const workflow = buildWorkflow(
    manifest,
    repo.manifestPath,
    fallbackAgent,
    warnings,
    workflowId,
    workflowRetryMaxAttempts,
  );

  const agentPaths: string[] = [];
  for (const agent of repo.agents) {
    const agentId = slug(agent.name);
    if (!agentId) {
      warnings.push(`Skipping agent at ${agent.path}; could not derive a valid id.`);
      continue;
    }
    const agentFolder = join(agentsDir, agentId);
    ensureDir(agentFolder);

    writeFileSync(join(agentFolder, "system-prompt.md"), agent.rawBody, "utf8");
    writeFileSync(join(agentFolder, "agent.json"), `${JSON.stringify({
      id: agentId,
      name: agent.name,
      role: agent.description || `${agent.name} specialist generated by Agent Forge`,
      systemPrompt: `agents/${agentId}/system-prompt.md`,
      skills: [],
      model: {
        tier: tierForModel(agent.model),
        preferredModel: agent.model,
      },
      memory: {
        enabled: true,
        namespace: `${packageId}/${agentId}`,
      },
      permissions: {
        network: false,
      },
    }, null, 2)}\n`, "utf8");

    agentPaths.push(`agents/${agentId}/agent.json`);
  }

  if (agentPaths.length === 0) {
    throw new Error("No agents were exported. Generate the Forge agent team before compiling a workforce package.");
  }

  const skillPaths: string[] = [];
  for (const skill of repo.skills) {
    const skillId = slug(skill.name || relative(repo.repoRoot, skill.path));
    if (!skillId) {
      warnings.push(`Skipping skill at ${skill.path}; could not derive a valid id.`);
      continue;
    }
    const skillFolder = join(skillsDir, skillId);
    ensureDir(skillFolder);
    writeFileSync(join(skillFolder, "SKILL.md"), readFileSync(skill.path, "utf8"), "utf8");
    skillPaths.push(`skills/${skillId}/SKILL.md`);
  }

  const workflowPath = join(workflowsDir, `${workflowId}.json`);
  writeFileSync(workflowPath, `${JSON.stringify(workflow, null, 2)}\n`, "utf8");

  const workforceManifestPath = join(workforceDir, "workforce.json");
  writeFileSync(workforceManifestPath, `${JSON.stringify({
    specVersion: "1.0",
    id: packageId,
    name: packageName,
    version: packageVersion,
    description: "Generated by forge-workforce-compiler from Agent Forge execution artifacts.",
    domain: "software-delivery",
    authors: ["Agent Forge"],
    license: "MIT",
    agents: agentPaths,
    skills: skillPaths,
    workflows: [`workflows/${workflowId}.json`],
    permissions: {
      network: false,
      fileSystem: false,
    },
    branding: {
      displayName: packageName,
      primaryColor: "#6366f1",
    },
  }, null, 2)}\n`, "utf8");

  const taskNodeMap = flattenTasks(manifest).map((task) => ({
    taskId: task.id,
    taskTitle: task.title,
    ownerAgent: task.ownerAgent,
    workflowNodeId: safeTaskNodeId(task.id),
  }));

  const bridgePath = join(repo.repoRoot, "docs", "KERNEL-BRIDGE.json");
  writeFileSync(bridgePath, `${JSON.stringify({
    generatedAt: new Date().toISOString(),
    mode: "flowforge-kernel",
    sourceOfTruth: "workforce-runtime",
    manifestPath: relative(repo.repoRoot, repo.manifestPath),
    workflowStatePath: relative(repo.repoRoot, repo.statePath),
    executionAuditPath: relative(repo.repoRoot, repo.auditPath),
    workforcePath: relative(repo.repoRoot, workforceDir),
    workflowId,
    taskNodeMap,
    warnings,
  }, null, 2)}\n`, "utf8");

  return {
    workforceDir,
    workforceManifestPath,
    workflowPath,
    bridgePath,
    warnings,
  };
}
