// <auto-generated />
using HumanGateway.Edge.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HumanGateway.Edge.Storage.Migrations
{
    [DbContext(typeof(EdgeDbContext))]
    [Migration("20260828233641_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("HumanGateway.Edge.Storage.Entities.ArtifactRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Envelope")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("json");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("hash");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("mime_type");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("size_bytes");

                    b.HasKey("Id");

                    b.HasIndex("Hash")
                        .HasDatabaseName("ix_artifacts_hash");

                    b.ToTable("artifacts", (string)null);
                });

            modelBuilder.Entity("HumanGateway.Edge.Storage.Entities.Conversation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("conversations", (string)null);
                });

            modelBuilder.Entity("HumanGateway.Edge.Storage.Entities.ConversationParticipant", b =>
                {
                    b.Property<string>("ConversationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("conversation_id");

                    b.Property<string>("ParticipantAddress")
                        .HasColumnType("TEXT")
                        .HasColumnName("participant_address");

                    b.Property<string>("JoinedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("joined_at");

                    b.HasKey("ConversationId", "ParticipantAddress");

                    b.HasIndex("ParticipantAddress");

                    b.ToTable("conversation_participants", (string)null);
                });

            modelBuilder.Entity("HumanGateway.Edge.Storage.Entities.DeliveryRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Envelope")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("json");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("message_id");

                    b.Property<string>("RecipientAddress")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("recipient_address");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("state");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .HasDatabaseName("ix_deliveries_message_id");

                    b.HasIndex("RecipientAddress")
                        .HasDatabaseName("ix_deliveries_recipient_address");

                    b.HasIndex("State")
                        .HasDatabaseName("ix_deliveries_state");

                    b.HasIndex("MessageId", "RecipientAddress")
                        .IsUnique()
                        .HasDatabaseName("ux_deliveries_message_recipient");

                    b.ToTable("deliveries", (string)null);
                });

            modelBuilder.Entity("HumanGateway.Edge.Storage.Entities.MessageRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content_hash");

                    b.Property<string>("ConversationId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("conversation_id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Envelope")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("json");

                    b.Property<string>("SenderAddress")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("sender_address");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId")
                        .HasDatabaseName("ix_messages_conversation_id");

                    b.HasIndex("SenderAddress")
                        .HasDatabaseName("ix_messages_sender_address");

                    b.HasIndex("ConversationId", "CreatedAt")
                        .HasDatabaseName("ix_messages_conversation_created");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("HumanGateway.Edge.Storage.Entities.ParticipantRecord", b =>
                {
                    b.Property<string>("Address")
                        .HasColumnType("TEXT")
                        .HasColumnName("address");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<string>("Envelope")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("json");

                    b.Property<string>("GatewayId")
                        .HasColumnType("TEXT")
                        .HasColumnName("gateway_id");

                    b.Property<string>("Kind")
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Address");

                    b.ToTable("participants", (string)null);
                });

            modelBuilder.Entity("HumanGateway.Edge.Storage.Entities.ConversationParticipant", b =>
                {
                    b.HasOne("HumanGateway.Edge.Storage.Entities.Conversation", "Conversation")
                        .WithMany("Participants")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HumanGateway.Edge.Storage.Entities.ParticipantRecord", "Participant")
                        .WithMany()
                        .HasForeignKey("ParticipantAddress")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("HumanGateway.Edge.Storage.Entities.Conversation", b =>
                {
                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
