// <auto-generated />
using System;
using HumanGateway.Relay.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HumanGateway.Relay.Storage.Migrations
{
    [DbContext(typeof(RelayDbContext))]
    [Migration("20260831195556_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HumanGateway.Relay.Storage.Entities.ArtifactBlobRecord", b =>
                {
                    b.Property<string>("Hash")
                        .HasColumnType("text")
                        .HasColumnName("hash");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_at");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("data");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.HasKey("Hash");

                    b.ToTable("artifact_blobs", (string)null);
                });

            modelBuilder.Entity("HumanGateway.Relay.Storage.Entities.ArtifactRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Envelope")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("json");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hash");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mime_type");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.HasKey("Id");

                    b.HasIndex("Hash")
                        .HasDatabaseName("ix_artifacts_hash");

                    b.ToTable("artifacts", (string)null);
                });

            modelBuilder.Entity("HumanGateway.Relay.Storage.Entities.Conversation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_at");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("text")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("conversations", (string)null);
                });

            modelBuilder.Entity("HumanGateway.Relay.Storage.Entities.ConversationParticipant", b =>
                {
                    b.Property<string>("ConversationId")
                        .HasColumnType("text")
                        .HasColumnName("conversation_id");

                    b.Property<string>("ParticipantAddress")
                        .HasColumnType("text")
                        .HasColumnName("participant_address");

                    b.Property<string>("JoinedAt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("joined_at");

                    b.HasKey("ConversationId", "ParticipantAddress");

                    b.HasIndex("ParticipantAddress");

                    b.ToTable("conversation_participants", (string)null);
                });

            modelBuilder.Entity("HumanGateway.Relay.Storage.Entities.DeliveryRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Envelope")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("json");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_id");

                    b.Property<string>("RecipientAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recipient_address");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .HasDatabaseName("ix_deliveries_message_id");

                    b.HasIndex("RecipientAddress")
                        .HasDatabaseName("ix_deliveries_recipient_address");

                    b.HasIndex("State")
                        .HasDatabaseName("ix_deliveries_state");

                    b.HasIndex("MessageId", "RecipientAddress")
                        .IsUnique()
                        .HasDatabaseName("ux_deliveries_message_recipient");

                    b.ToTable("deliveries", (string)null);
                });

            modelBuilder.Entity("HumanGateway.Relay.Storage.Entities.GatewayRecord", b =>
                {
                    b.Property<string>("GatewayId")
                        .HasColumnType("text")
                        .HasColumnName("gateway_id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("LastSeenAt")
                        .HasColumnType("text")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("RegisteredAt")
                        .HasColumnType("text")
                        .HasColumnName("registered_at");

                    b.Property<string>("RegistrationTokenFingerprint")
                        .HasColumnType("text")
                        .HasColumnName("registration_token_fingerprint");

                    b.Property<string>("RevokedAt")
                        .HasColumnType("text")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("SuspendedAt")
                        .HasColumnType("text")
                        .HasColumnName("suspended_at");

                    b.Property<string>("TokenExpiresAt")
                        .HasColumnType("text")
                        .HasColumnName("token_expires_at");

                    b.Property<string>("TokenIssuedAt")
                        .HasColumnType("text")
                        .HasColumnName("token_issued_at");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("text")
                        .HasColumnName("updated_at");

                    b.HasKey("GatewayId");

                    b.HasIndex("LastSeenAt")
                        .HasDatabaseName("ix_gateways_last_seen_at");

                    b.HasIndex("RegistrationTokenFingerprint")
                        .IsUnique()
                        .HasDatabaseName("ux_gateways_token_fingerprint");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_gateways_status");

                    b.ToTable("gateways", (string)null);
                });

            modelBuilder.Entity("HumanGateway.Relay.Storage.Entities.IdempotencyRecord", b =>
                {
                    b.Property<string>("BatchId")
                        .HasColumnType("text")
                        .HasColumnName("batch_id");

                    b.Property<string>("IdempotencyKey")
                        .HasColumnType("text")
                        .HasColumnName("idempotency_key");

                    b.Property<DateTimeOffset>("AppliedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at_utc");

                    b.HasKey("BatchId", "IdempotencyKey");

                    b.ToTable("idempotency", (string)null);
                });

            modelBuilder.Entity("HumanGateway.Relay.Storage.Entities.InboxEntryRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("GatewayId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gateway_id");

                    b.Property<string>("Item")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("json");

                    b.Property<string>("MessageId")
                        .HasColumnType("text")
                        .HasColumnName("message_id");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at_utc");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .IsUnique()
                        .HasDatabaseName("ux_inbox_message_id");

                    b.HasIndex("GatewayId", "Sequence")
                        .HasDatabaseName("ix_inbox_gateway_sequence");

                    b.ToTable("inbox", (string)null);
                });

            modelBuilder.Entity("HumanGateway.Relay.Storage.Entities.MessageRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_hash");

                    b.Property<string>("ConversationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("conversation_id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_at");

                    b.Property<string>("Envelope")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("json");

                    b.Property<string>("SenderAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sender_address");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId")
                        .HasDatabaseName("ix_messages_conversation_id");

                    b.HasIndex("SenderAddress")
                        .HasDatabaseName("ix_messages_sender_address");

                    b.HasIndex("ConversationId", "CreatedAt")
                        .HasDatabaseName("ix_messages_conversation_created");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("HumanGateway.Relay.Storage.Entities.ParticipantRecord", b =>
                {
                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Envelope")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("json");

                    b.Property<string>("GatewayId")
                        .HasColumnType("text")
                        .HasColumnName("gateway_id");

                    b.Property<string>("Kind")
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Address");

                    b.ToTable("participants", (string)null);
                });

            modelBuilder.Entity("HumanGateway.Relay.Storage.Entities.SyncCursorRecord", b =>
                {
                    b.Property<string>("GatewayId")
                        .HasColumnType("text")
                        .HasColumnName("gateway_id");

                    b.Property<string>("PullCursor")
                        .HasColumnType("text")
                        .HasColumnName("pull_cursor");

                    b.Property<string>("PushCursor")
                        .HasColumnType("text")
                        .HasColumnName("push_cursor");

                    b.HasKey("GatewayId");

                    b.ToTable("sync_cursors", (string)null);
                });

            modelBuilder.Entity("HumanGateway.Relay.Storage.Entities.ConversationParticipant", b =>
                {
                    b.HasOne("HumanGateway.Relay.Storage.Entities.Conversation", "Conversation")
                        .WithMany("Participants")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HumanGateway.Relay.Storage.Entities.ParticipantRecord", "Participant")
                        .WithMany()
                        .HasForeignKey("ParticipantAddress")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("HumanGateway.Relay.Storage.Entities.Conversation", b =>
                {
                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
